name: multimodal_meta_learn
channels:
  - defaults
dependencies:
- python>=3.8
- pip>=22
- scikit-image=0.19.2
- matplotlib
- numpy
- pip:
   - tokenizers==0.13.2
   - torch==1.12.1
   - torchvision==0.13.1
   - transformers==4.25.1
   - ftfy
   - regex
   - tqdm
   - gdown
   - Pillow
   - git+https://github.com/openai/CLIP.git